--P2Q3
--QUERY TO PRINT THE NAME OF EACH EMPLOYEES HAVING THE HIGHEST SALARY IN EACH DEPT

SELECT CONCAT(FIRST_NAME, LAST_NAME) AS COMPLETE_NAME, SALARY 
FROM Worker 
WHERE SALARY IN (SELECT DISTINCT MAX(SALARY) FROM Worker GROUP BY DEPARTMENT)

--P2Q4
--QUERY THAT RETURNS THE MAXIMUM BONUS AMOUNT OF AN EXECUTIVE WORKER

SELECT MAX(BONUS_AMOUNT) AS EXECUTIVE_MAX_BONUS_AMOUNT
FROM Bonus AS B
INNER JOIN Title AS T
ON B.WORKER_REF_ID = T.WORKER_REF_ID
WHERE T.WORKER_TITLE = 'Executive' AND YEAR(BONUS_DATE) = 2016

